#!/bin/sh

startup_path=$1
hardware_id=$2
device_id=$3
status=$4
status2=$5
devname=$6

echo "startup_path=${startup_path}, hardware_id=${hardware_id}, device_id=${device_id}, status=${status}, status2=${status2}, devname=${devname}"

//Living TV
if [ "$device_id" = "137" ] ; then
	if [ "$status" = "On" ] ; then
		exec `home/pi/HarmonyHubControl/HarmonyHubControl erikvennink@gmail.com ecokey4281 10.0.1.107 start_activity 6057248` &
	fi
fi

//Living Apple TV
if [ "$device_id" = "138" ] ; then
	if [ "$status" = "On" ] ; then
		exec `home/pi/HarmonyHubControl/HarmonyHubControl erikvennink@gmail.com ecokey4281 10.0.1.107 start_activity 8652728` &
	fi
fi

//Living Smart TV
if [ "$device_id" = "139" ] ; then
	if [ "$status" = "On" ] ; then
		exec `home/pi/HarmonyHubControl/HarmonyHubControl erikvennink@gmail.com ecokey4281 10.0.1.107 start_activity 12095646` &
	fi
fi

//Living Playstation
if [ "$device_id" = "140" ] ; then
	if [ "$status" = "On" ] ; then
		exec `home/pi/HarmonyHubControl/HarmonyHubControl erikvennink@gmail.com ecokey4281 10.0.1.107 start_activity 8586172` &
	fi
fi

//Living Sonos
if [ "$device_id" = "141" ] ; then
	if [ "$status" = "On" ] ; then
		exec `home/pi/HarmonyHubControl/HarmonyHubControl erikvennink@gmail.com ecokey4281 10.0.1.107 start_activity 9276052` &
	fi
fi

//Living On
if [ "$device_id" = "136" ] ; then
	if [ "$status" = "Off" ] ; then
		exec `home/pi/HarmonyHubControl/HarmonyHubControl erikvennink@gmail.com ecokey4281 10.0.1.107 start_activity -1` &
	fi
fi
